[window.dimensions]
columns = 150
lines = 35

[window]
opacity = 0.9

[general]
import = ["colors.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

# Copy
[keyboard]
bindings = [
    { key = "C", mods = "Control", action = "Copy"},
    { key = "V", mods = "Control", action = "Paste"},
    { key = "C", mods = "Control|Shift", chars = "\u0003"},
    { key = "Return", mods = "Shift", chars = "\u001B\r"}
]
