[colors.primary]
background = '#0c141b'
foreground = '#dbe3ed'
 
[colors.cursor]
text = '#dbe3ed'
cursor = '#b7c9d9' 
 
[colors.vi_mode_cursor]
text = '#0c141b'
cursor = '#4edad4' 
 
[colors.search.matches]
foreground = '#384956' 
background = '#96cdf8' 
 
[colors.search.focused_match]
foreground = '#384956' 
background = '#4edad4' 
 
[colors.footer_bar]
foreground = '#384956' 
background = '#dbe3ed' 
 
[colors.hints.start]
foreground = '#384956' 
background = '#80d5d0' 
 
[colors.hints.end]
foreground = '#384956' 
background = '#80d5d0' 
 
[colors.selection]
text = '#0c141b'
background = '#4edad4'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#4edad4' 
yellow = '#006a66' 
blue = '#4edad4' 
magenta = '#96cdf8' 
cyan = '#80d5d0' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 