[colors.primary]
background = '#11140e'
foreground = '#e2e3d9'
 
[colors.cursor]
text = '#e2e3d9'
cursor = '#c4c8ba' 
 
[colors.vi_mode_cursor]
text = '#11140e'
cursor = '#add28e' 
 
[colors.search.matches]
foreground = '#44483e' 
background = '#a0cfce' 
 
[colors.search.focused_match]
foreground = '#44483e' 
background = '#add28e' 
 
[colors.footer_bar]
foreground = '#44483e' 
background = '#e2e3d9' 
 
[colors.hints.start]
foreground = '#44483e' 
background = '#becbae' 
 
[colors.hints.end]
foreground = '#44483e' 
background = '#becbae' 
 
[colors.selection]
text = '#11140e'
background = '#add28e'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#add28e' 
yellow = '#47672f' 
blue = '#add28e' 
magenta = '#a0cfce' 
cyan = '#becbae' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 