tab = "playback"
tabs = [ "playback", "output", "input", "recording", "configuration" ]
keybindings = [
    { key = "Esc", action = "Exit" },
]

theme = "matugen"

[themes.matugen]
inherit = "default"

# Selection indicators
selector = { fg = "#ffb4a8" }

# Tab styling
tab = { fg = "#eabcb4" }
tab_selected = { fg = "#ffb4a8" }
tab_marker = { fg = "#afc6ff" }

# List overflow indicators
list_more = { fg = "#b08780" }

# Node info
node_title = { fg = "#ffdad4" }
node_target = { fg = "#eabcb4" }

# Volume
volume = { fg = "#ffdad4" }
volume_empty = { fg = "#5f3e39" }
volume_filled = { fg = "#ffb4a8" }

# Peak meter
meter_inactive = { fg = "#5f3e39" }
meter_active = { fg = "#afc6ff" }
meter_overload = { fg = "#ffb4ab" }
meter_center_inactive = { fg = "#b08780" }
meter_center_active = { fg = "#538dff" }

# Config tab
config_device = { fg = "#ffdad4" }
config_profile = { fg = "#ffb4a8" }

# Dropdowns
dropdown_icon = { fg = "#ffb4a8" }
dropdown_border = { fg = "#b08780" }
dropdown_item = { fg = "#ffdad4" }
dropdown_selected = { fg = "#690000", bg = "#ffb4a8" }
dropdown_more = { fg = "#b08780" }

# Help menu
help_border = { fg = "#b08780" }
help_item = { fg = "#eabcb4" }
help_more = { fg = "#b08780" }
