tab = "playback"
tabs = [ "playback", "output", "input", "recording", "configuration" ]
keybindings = [
    { key = "Esc", action = "Exit" },
]

theme = "matugen"

[themes.matugen]
inherit = "default"

# Selection indicators
selector = { fg = "#f8acff" }

# Tab styling
tab = { fg = "#d1c2ce" }
tab_selected = { fg = "#f8acff" }
tab_marker = { fg = "#f8b3d1" }

# List overflow indicators
list_more = { fg = "#9a8d98" }

# Node info
node_title = { fg = "#eedeeb" }
node_target = { fg = "#d1c2ce" }

# Volume
volume = { fg = "#eedeeb" }
volume_empty = { fg = "#4e434e" }
volume_filled = { fg = "#e6bad7" }

# Peak meter
meter_inactive = { fg = "#4e434e" }
meter_active = { fg = "#f8b3d1" }
meter_overload = { fg = "#ffb4ab" }
meter_center_inactive = { fg = "#9a8d98" }
meter_center_active = { fg = "#69364f" }

# Config tab
config_device = { fg = "#eedeeb" }
config_profile = { fg = "#e6bad7" }

# Dropdowns
dropdown_icon = { fg = "#f8acff" }
dropdown_border = { fg = "#9a8d98" }
dropdown_item = { fg = "#eedeeb" }
dropdown_selected = { fg = "#570067", bg = "#f8acff" }
dropdown_more = { fg = "#9a8d98" }

# Help menu
help_border = { fg = "#9a8d98" }
help_item = { fg = "#d1c2ce" }
help_more = { fg = "#9a8d98" }
