[config]
version_check = false

[templates.mango]
input_path = '~/.config/matugen/templates/mango.conf'
output_path = '~/.config/mango/mango-colors.conf'
post_hook = 'mmsg -d reload_config'

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/mango/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.btop]
input_path = "~/.config/matugen/templates/btop.theme"
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync-colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/shared/colors.rasi"

[templates.alacritty]
input_path = "~/.config/matugen/templates/alacritty.toml"
output_path = "~/.config/alacritty/colors.toml"

[templates.equibop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/equibop/themes/midnight-discord.css'

[templates.steam]
input_path = '~/.config/matugen/templates/steam.css'
output_path = '~/.config/AdwSteamGtk/custom.css'
post_hook =  'adwaita-steam-gtk -i'

[templates.opencode]
input_path = '~/.config/matugen/templates/opencode.json'
output_path = '~/.config/opencode/themes/matugen.json'

[templates.vscode]
input_path = '~/.config/matugen/templates/vscode.json'
output_path = '~/.config/Code/User/settings.json'

[templates.neovim]
input_path = "~/.config/matugen/templates/neovim.lua"
output_path = "~/.config/nvim/lua/plugins/matugen-colors.lua"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"