$image = /mnt/b27299bf-cb8e-44de-a901-039f69aa5feb/archive/picturesarchive/wallpapers/yurucampforest.png

$background = rgba(191306ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(372f20ff)

$inverse_primary = rgba(9b4427ff)

$inverse_surface = rgba(efe1caff)

$on_background = rgba(efe1caff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(5e1800ff)

$on_primary_container = rgba(ffdbd0ff)

$on_primary_fixed = rgba(3a0b00ff)

$on_primary_fixed_variant = rgba(7c2d12ff)

$on_secondary = rgba(561f0dff)

$on_secondary_container = rgba(ffdbd0ff)

$on_secondary_fixed = rgba(3a0b00ff)

$on_secondary_fixed_variant = rgba(723521ff)

$on_surface = rgba(efe1caff)

$on_surface_variant = rgba(d8c4a0ff)

$on_tertiary = rgba(402e00ff)

$on_tertiary_container = rgba(ffdf9eff)

$on_tertiary_fixed = rgba(261a00ff)

$on_tertiary_fixed_variant = rgba(5b4300ff)

$outline = rgba(a08f6eff)

$outline_variant = rgba(52452aff)

$primary = rgba(ffb59eff)

$primary_container = rgba(7c2d12ff)

$primary_fixed = rgba(ffdbd0ff)

$primary_fixed_dim = rgba(ffb59eff)

$scrim = rgba(000000ff)

$secondary = rgba(ffb59eff)

$secondary_container = rgba(723521ff)

$secondary_fixed = rgba(ffdbd0ff)

$secondary_fixed_dim = rgba(ffb59eff)

$shadow = rgba(000000ff)

$source_color = rgba(caa34cff)

$surface = rgba(191306ff)

$surface_bright = rgba(403828ff)

$surface_container = rgba(261f11ff)

$surface_container_high = rgba(30291aff)

$surface_container_highest = rgba(3c3424ff)

$surface_container_low = rgba(211b0dff)

$surface_container_lowest = rgba(130d03ff)

$surface_dim = rgba(191306ff)

$surface_tint = rgba(ffb59eff)

$surface_variant = rgba(52452aff)

$tertiary = rgba(e9c16cff)

$tertiary_container = rgba(5b4300ff)

$tertiary_fixed = rgba(ffdf9eff)

$tertiary_fixed_dim = rgba(e9c16cff)

