$image = /mnt/b27299bf-cb8e-44de-a901-039f69aa5feb/archive/picturesarchive/wallpapers/desktop/persona5bg.jpg

$background = rgba(11131cff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2e303aff)

$inverse_primary = rgba(006782ff)

$inverse_surface = rgba(e2e1efff)

$on_background = rgba(e2e1efff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(003545ff)

$on_primary_container = rgba(bbe9ffff)

$on_primary_fixed = rgba(001f29ff)

$on_primary_fixed_variant = rgba(004d63ff)

$on_secondary = rgba(003545ff)

$on_secondary_container = rgba(bbe9ffff)

$on_secondary_fixed = rgba(001f29ff)

$on_secondary_fixed_variant = rgba(004d63ff)

$on_surface = rgba(e2e1efff)

$on_surface_variant = rgba(c3c5ddff)

$on_tertiary = rgba(202c61ff)

$on_tertiary_container = rgba(dde1ffff)

$on_tertiary_fixed = rgba(07164bff)

$on_tertiary_fixed_variant = rgba(374379ff)

$outline = rgba(8d8fa6ff)

$outline_variant = rgba(424659ff)

$primary = rgba(61d4ffff)

$primary_container = rgba(004d63ff)

$primary_fixed = rgba(bbe9ffff)

$primary_fixed_dim = rgba(61d4ffff)

$scrim = rgba(000000ff)

$secondary = rgba(8ad0eeff)

$secondary_container = rgba(004d63ff)

$secondary_fixed = rgba(bbe9ffff)

$secondary_fixed_dim = rgba(8ad0eeff)

$shadow = rgba(000000ff)

$source_color = rgba(1b1d28ff)

$surface = rgba(11131cff)

$surface_bright = rgba(373943ff)

$surface_container = rgba(1d1f29ff)

$surface_container_high = rgba(282934ff)

$surface_container_highest = rgba(33343fff)

$surface_container_low = rgba(191b25ff)

$surface_container_lowest = rgba(0c0e17ff)

$surface_dim = rgba(11131cff)

$surface_tint = rgba(61d4ffff)

$surface_variant = rgba(424659ff)

$tertiary = rgba(b8c3ffff)

$tertiary_container = rgba(374379ff)

$tertiary_fixed = rgba(dde1ffff)

$tertiary_fixed_dim = rgba(b8c3ffff)

