$image = /mnt/b27299bf-cb8e-44de-a901-039f69aa5feb/archive/picturesarchive/wallpapers/desktop/let us start the game ps3 xmb background persona 5.jpg

$background = rgba(1e100eff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(3d2c29ff)

$inverse_primary = rgba(8c4381ff)

$inverse_surface = rgba(f9dcd8ff)

$on_background = rgba(f9dcd8ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(561250ff)

$on_primary_container = rgba(ffd7f2ff)

$on_primary_fixed = rgba(390035ff)

$on_primary_fixed_variant = rgba(712b68ff)

$on_secondary = rgba(4d1f47ff)

$on_secondary_container = rgba(ffd7f2ff)

$on_secondary_fixed = rgba(340830ff)

$on_secondary_fixed_variant = rgba(67355eff)

$on_surface = rgba(f9dcd8ff)

$on_surface_variant = rgba(e7bdb6ff)

$on_tertiary = rgba(561e16ff)

$on_tertiary_container = rgba(ffdad4ff)

$on_tertiary_fixed = rgba(3a0905ff)

$on_tertiary_fixed_variant = rgba(73342bff)

$outline = rgba(ae8882ff)

$outline_variant = rgba(5d3f3bff)

$primary = rgba(ffabedff)

$primary_container = rgba(712b68ff)

$primary_fixed = rgba(ffd7f2ff)

$primary_fixed_dim = rgba(ffabedff)

$scrim = rgba(000000ff)

$secondary = rgba(f3b2e3ff)

$secondary_container = rgba(67355eff)

$secondary_fixed = rgba(ffd7f2ff)

$secondary_fixed_dim = rgba(f3b2e3ff)

$shadow = rgba(000000ff)

$source_color = rgba(f10503ff)

$surface = rgba(1e100eff)

$surface_bright = rgba(473532ff)

$surface_container = rgba(2b1c19ff)

$surface_container_high = rgba(372623ff)

$surface_container_highest = rgba(42312eff)

$surface_container_low = rgba(271815ff)

$surface_container_lowest = rgba(180b09ff)

$surface_dim = rgba(1e100eff)

$surface_tint = rgba(ffabedff)

$surface_variant = rgba(5d3f3bff)

$tertiary = rgba(ffb4a8ff)

$tertiary_container = rgba(73342bff)

$tertiary_fixed = rgba(ffdad4ff)

$tertiary_fixed_dim = rgba(ffb4a8ff)

