general {
    lock_cmd = pidof hyprlock || hyprlock           # command to run on loginctl lock-session
    before_sleep_cmd = loginctl lock-session        # run before system sleeps
    after_sleep_cmd = sleep 2; ~/.config/hypr/scripts/brightness.sh 100
}

listener {
    timeout = 300                                   # 5min
    # on-timeout = brightnessctl -s set 10          # lower monitor brightness, avoid 0 with OLED monitors
    # on-resume = brightnessctl -r                  # restore monitor brightness
}

listener {
    timeout = 600                                   # 10 min
    on-timeout = loginctl lock-session
}

listener {
    timeout = 900                                   # 15 min
    on-timeout = ~/.config/hypr/scripts/brightness.sh 1
}
