general {
    lock_cmd = pidof hyprlock || hyprlock           # command to run on loginctl lock-session
    before_sleep_cmd = loginctl lock-session        # run before system sleeps
    after_sleep_cmd = wlopm --on \* && (pidof hyprlock || hyprlock)    # re-lock after waking
}

listener {
    timeout = 150                                   # 2.5min.
    on-timeout = brightnessctl -s set 10            # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                    # monitor backlight restore.
}

listener {
    timeout = 600                                   # 10 min
    on-timeout = loginctl lock-session
}

listener {
    timeout = 900                                   # 15 min
    on-timeout = wlopm --off \*
    on-resume = wlopm --on \*
}
