# set keyboard
xkb_rules_layout=gb

# mouse
mouse_natural_scrolling=0

# apps
bind=SUPER,Return,spawn,alacritty
bind=SUPER,space,spawn,rofi -modes "drun" -show "drun" -m DP-1
bind=SUPER+SHIFT,r,reload_config
bind=SUPER+SHIFT,w,spawn,killall -SIGUSR2 waybar
bind=SUPER,l,spawn,loginctl lock-session
bind=SUPER,b,spawn,helium-browser
bind=SUPER,e,spawn,nautilus
bind=SUPER,z,spawn,zed
bind=SUPER,v,spawn,alacritty --title 'clipse' -e clipse

# screenshotting
bind=NONE,Print,spawn,~/.config/mango/scripts/screenshot.sh
bind=CTRL,Print,spawn,~/.config/mango/scripts/screenshot.sh select
bind=Shift,Print,spawn,~/.config/mango/scripts/screenrecord.sh
bind=CTRL+SHIFT,Print,spawn,~/.config/mango/scripts/screenrecord.sh select

# tags
bind=SUPER,Left,viewtoleft,0
bind=SUPER,Right,viewtoright,0
bind=SUPER+CTRL,Left,tagtoleft,0
bind=SUPER+CTRL,Right,tagtoright,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# window focus
#bind=SUPER,Left,focusdir,left
#bind=SUPER,Right,focusdir,right
#bind=SUPER,Down,focusdir,up
#bind=SUPER,Up,focusdir,down
#bind=SUPER+SHIFT,Left,focusmon,left
#bind=SUPER+SHIFT,Right,focusmon,right

# window movement
#bind=SUPER+SHIFT,Left,resizewin,-10,0
#bind=SUPER+SHIFT,Right,resizewin,+10,0
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# swap window
bind=SUPER+SHIFT,left,exchange_client,left
bind=SUPER+SHIFT,right,exchange_client,right
bind=SUPER+SHIFT,up,exchange_client,up
bind=SUPER+SHIFT,down,exchange_client,down
bind=SUPER+CTRL+SHIFT,Left,tagmon,left
bind=SUPER+CTRL+SHIFT,Right,tagmon,right

# window management
bind=SUPER,q,killclient
bind=ALT,Tab,toggleoverview
bind=SUPER,Tab,focusstack,next
bind=SUPER,g,toggleglobal
bind=SUPER,o,toggleoverlay
bind=SUPER,f,togglefloating
bind=SUPER,t,switch_layout
bind=SUPER,m,minimized
bind=SUPER+CTRL,m,restore_minimized
bind=SUPER+ALT,m,toggle_scratchpad

# gaps
bind=ALT+SHIFT,x,incgaps,1
bind=ALT+SHIFT,z,incgaps,-1
bind=ALT+SHIFT,r,togglegaps

# volume/media keys
bind=NONE,XF86AudioRaiseVolume,spawn,pactl set-sink-volume @DEFAULT_SINK@ +5%
bind=NONE,XF86AudioLowerVolume,spawn,pactl set-sink-volume @DEFAULT_SINK@ -5%
bind=NONE,XF86AudioMute,spawn,pactl set-sink-mute @DEFAULT_SINK@ toggle
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause
bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioPrev,spawn,playerctl previous
bind=NONE,XF86AudioStop,spawn,playerctl stop
