# set english UK keyboard
xkb_rules_layout=gb

# mouse
mouse_natural_scrolling=0

# generic
bind=SUPER,Return,spawn,alacritty
bind=SUPER,q,killclient,
bind=SUPER,space,spawn,rofi -show drun
bind=SUPER+SHIFT,r,reload_config
bind=SUPER,l,spawn,loginctl lock-session

# movement
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Down,focusdir,up
bind=SUPER,Up,focusdir,down

bind=SUPER+ALT,Left,tagmon,left
bind=SUPER+ALT,Right,tagmon,right

bind=SUPER+CTRL,Left,focusmon,left
bind=SUPER+CTRL,Right,focusmon,right

bind=SUPER+SHIFT,Left,resizewin,-10,0
bind=SUPER+SHIFT,Right,resizewin,+10,0

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# window management
bind=ALT,Tab,toggleoverview
bind=SUPER,o,toggleoverlay
bind=SUPER,f,togglefloating
bind=SUPER,n,switch_layout
bind=SUPER,m,minimized
bind=SUPER+CTRL,m,restore_minimized

# gaps
bind=ALT+SHIFT,x,incgaps,1
bind=ALT+SHIFT,z,incgaps,-1
bind=ALT+SHIFT,r,togglegaps

# volume keys
bind=NONE,XF86AudioRaiseVolume,spawn,pactl set-sink-volume @DEFAULT_SINK@ +5%
bind=NONE,XF86AudioLowerVolume,spawn,pactl set-sink-volume @DEFAULT_SINK@ -5%
bind=NONE,XF86AudioMute,spawn,pactl set-sink-mute @DEFAULT_SINK@ toggle

bind=NONE,XF86AudioPlay,spawn,playerctl play-pause
bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioPrev,spawn,playerctl previous
bind=NONE,XF86AudioStop,spawn,playerctl stop

# launch programs
bind=SUPER,b,spawn,helium-browser
bind=SUPER,e,spawn,nautilus
