# misc
syncobj_enable=1
sloppyfocus=0
warpcursor=1
enable_hotarea=0
allow_tearing=2

# load configs
source=./env.conf
source=./binds.conf
source=./monitor.conf
source=./visuals.conf
source=./windowrules.conf

# run autostart
exec-once = ~/.config/mango/autostart.sh
