source=./binds.conf
source=./style.conf
source=./monitor.conf
source=./windowrules.conf

# misc
syncobj_enable=1
adaptive_sync=1
allow_tearing=2
focus_on_activate=1
sloppyfocus=0
warpcursor=1
enable_hotarea=0
ov_tab_mode=1

# autostart
exec-once = ~/.config/mango/autostart.sh
