# misc
syncobj_enable=1
sloppyfocus=0
warpcursor=1
enable_hotarea=0
allow_tearing=0

# load configs
source=./env.conf
source=./binds.conf
source=./monitor.conf
source=./visuals.conf
source=./windowrules.conf

# run autostart
exec-once = ~/.config/mango/autostart.sh

# https://github.com/mangowm/mango/issues/1043
exec-once=systemctl --user start xdg-desktop-portal.service --ignore-dependencies &
