# Keyboard
xkb_rules_layout=gb
xkb_rules_options=compose:menu

# Mouse
mouse_accel_profile=1
mouse_accel_speed=0.5
mouse_natural_scrolling=0

# Trackpad
trackpad_natural_scrolling=1
disable_while_typing=0
