shadowscolor = 0x000000ff
rootcolor = 0x210e0bff
bordercolor = 0xb08780ff
focuscolor = 0xffb4a8ff
maximizescreencolor = 0xffb4a8ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xffb954ff
globalcolor = 0x452b00ff
overlaycolor = 0x690000ff