shadowscolor = 0x000000ff
rootcolor = 0x0c150eff
bordercolor = 0x829682ff
focuscolor = 0xdac84eff
maximizescreencolor = 0xd6c870ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0x9ad4a2ff
globalcolor = 0x003917ff
overlaycolor = 0x373100ff