shadowscolor = 0x000000ff
rootcolor = 0x0e150cff
bordercolor = 0x85957eff
focuscolor = 0xe7c349ff
maximizescreencolor = 0xe0c56dff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xa3d398ff
globalcolor = 0x0e380dff
overlaycolor = 0x3c2f00ff