windowrule=isfloating:1,appid:^(.*)$
windowrule=force_tearing:0,appid:mpv

windowrule=isfloating:0,appid:zed
windowrule=isfloating:0,appid:helium
windowrule=isfloating:0,appid:com.obsproject.Studio

windowrule=isfloating:1,isoverlay:1,isglobal:1,ignore_maximize:1,ignore_minimize:1,width:400,height:225,offsetx:95,offsety:95,title:Picture-in-picture

windowrule=isfloating:1,appid:steam
windowrule=isfloating:0,appid:steam,title:Steam Big Picture Mode

windowrule=isfloating:1,width:1360,height:765,appid:org.gnome.Nautilus
windowrule=isfloating:1,width:1360,height:765,appid:org.gnome.FileRoller
windowrule=isfloating:1,width:1360,height:765,appid:xdg-desktop-portal-gtk

windowrule=isfloating:1,width:650,height:800,offsetx:100,offsety:-100,animation_type_open:slide,animation_type_close:none,title:clipse,appid:Alacritty
windowrule=isfloating:1,width:720,height:800,offsetx:100,offsety:-100,animation_type_open:slide,animation_type_close:none,title:wlctl,appid:Alacritty
windowrule=isfloating:1,width:600,height:650,offsetx:100,offsety:-100,animation_type_open:slide,animation_type_close:none,title:bluetui,appid:Alacritty
windowrule=isfloating:1,width:600,height:650,offsetx:100,offsety:-100,animation_type_open:slide,animation_type_close:none,title:wiremix,appid:Alacritty
