# mpv
windowrule=isfloating:1,appid:mpv

# qimgv
windowrule=isfloating:1,appid:qimgv

# Steam
windowrule=isfloating:1,scroller_proportion:0.3,appid:^steam$,title:^Friends List$
windowrule=isfloating:1,scroller_proportion:0.5,appid:^steam$,title:.*(Settings|Properties).*
windowrule=isfloating:1,appid:^steam$,title:^Steam - News$

windowrule=isfloating:1,appid:equibop
windowrule=isfloating:1,appid:nxapi-app

# PrismLauncher
windowrule=isfloating:1,appid:PrismLauncher
windowrule=isfloating:1,appid:Minecraft

windowrule=isfloating:1,width:400,height:225,offsetx:95,offsety:95,isnoborder:1,title:Picture-in-picture
windowrule=isfloating:1,appid=chrome-nngceckbapebfimnlniiiahkandclblb-Default
