# mpv
windowrule=isfloating:1,appid:mpv

# qimgv
windowrule=isfloating:1,appid:qimgv

# Steam
windowrule=isfloating:1,appid:steam
windowrule=isfloating:0,appid:steam,title:Steam Big Picture Mode

# PrismLauncher
windowrule=isfloating:1,appid:PrismLauncher
windowrule=isfloating:1,appid:Minecraft

windowrule=isfloating:1,appid:discord
windowrule=isfloating:1,appid:discord-canary
windowrule=isfloating:1,appid:nxapi-app
windowrule=isfloating:1,appid:fluent-reader
windowrule=isfloating:1,title:btop
windowrule=isfloating:1,title:Terminal
windowrule=isfloating:1,appid:winboat
windowrule=isfloating:1,appid:winboat-iTunes
windowrule=isfloating:1,appid:winboat-File Explorer
windowrule=isfloating:1,width:1400,height:788,appid:org.gnome.Nautilus
windowrule=isfloating:1,width:1400,height:788,appid:xdg-desktop-portal-gtk
windowrule=isfloating:1,width:450,height:550,offsetx:100,offsety:-100,title:clipse
windowrule=isfloating:1,width:450,height:550,offsetx:100,offsety:-100,title:wifitui
windowrule=isfloating:1,width:450,height:550,offsetx:100,offsety:-100,title:bluetui

windowrule=isfloating:1,isnoshadow:1,ignore_maximize:1,ignore_minimize:1,width:400,height:225,offsetx:95,offsety:95,isnoborder:1,title:Picture-in-picture
windowrule=isfloating:1,noopenmaximized:1,noblur:1,width:600,height:600,title:Bitwarden
