PROTON_DLSS_UPGRADE=1
DXVK_NVAPI_DRS_NGX_DLSS_SR_OVERRIDE_RENDER_PRESET_SELECTION=render_preset_c
PROTON_NVIDIA_LIBS=1

DXVK_NVAPI_VKREFLEX=1
PROTON_DXVK_LOWLATENCY=1
PROTON_VKD3D_LOWLATENCY=1

PROTON_LOCAL_SHADER_CACHE=1
PROTON_DISCORD_BRIDGE=1
