osc_color={{colors.shadow.default.hex}}
window_title_color=#FFFFFF
window_controls_color={{colors.on_surface_variant.default.hex}}
window_controls_close_hover={{colors.error.default.hex}}
window_controls_minmax_hover={{colors.secondary.default.hex}}
title_color=#FFFFFF
seekbarfg_color={{colors.primary.default.hex}}
seekbarbg_color={{colors.outline_variant.default.hex}}
seekbar_cache_color={{colors.secondary.default.hex}}
volumebar_match_seek_color=no
time_color={{colors.on_surface.default.hex}}
chapter_title_color={{colors.on_surface_variant.default.hex}}
chapter_marker_color={{colors.tertiary.default.hex}}
chapter_marker_current_color={{colors.primary.default.hex}}
side_buttons_color={{colors.on_surface_variant.default.hex}}
middle_buttons_color={{colors.on_surface.default.hex}}
playpause_color={{colors.primary.default.hex}}
held_element_color={{colors.outline.default.hex}}
hover_effect_color=#FFFFFF
thumbnail_border_color={{colors.primary.default.hex}}
thumbnail_border_outline=#FFFFFF

show_on_pause=no
ontop_button=no
seek_handle_size=0
show_youtube_comments=yes
FORCE_fix_not_ontop=no
